name: 'State Check'
description: 'Logs the state of the build.'

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        echo === GIT STATUS
        git status --verbose --branch --long
        echo
        echo === GIT BRANCH
        git branch -vv --all
        echo
        echo === GITHUB_WORKFLOW: The action name
        echo ${{ github.workflow }}
        echo
        echo === GITHUB_ACTOR: Ran by username
        echo ${{ github.actor }}
        echo
        echo === GITHUB_REPOSITORY
        echo ${{ github.repository }}
        echo
        echo === GITHUB_EVENT_NAME
        echo  ${{ github.event_name }}
        echo
        echo === GITHUB_SHA
        echo ${{ github.sha }}
        echo
        echo === GITHUB_REF
        echo ${{ github.ref }}
        echo
        echo === GITHUB_REF_NAME
        echo ${{ github.ref_name }}
        echo
        echo === GITHUB_REF_TYPE: branch or tag
        echo ${{ github.ref_type }}
        echo
        echo === GITHUB_HEAD_REF: Source of the change
        echo ${{ github.head_ref }}
        echo
        echo === GITHUB_BASE_REF: Target of the change
        echo ${{ github.base_ref }}
        echo
        echo === NODE VERSION
        node -v
        echo
        echo === SFDX CLI VERSION
        sfdx --version
        echo
        echo === SFDX PLUGINS
        sfdx plugins --core
