name: 'SFDX CLI Install'
description: 'Downloads SFDX CLI and sets up the path.'

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        wget https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
        mkdir sfdx-cli
        tar xJf sfdx-linux-x64.tar.xz -C sfdx-cli --strip-components 1
        echo "$( pwd )/sfdx-cli/bin" >> $GITHUB_PATH
