name: 'SFDX Deploy Build'
description: 'Deploys the changed metadata to the Org.'

inputs:
  unit-tests:
    description: 'Comma separated values of Apex Classes.'
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      run: sfdx force:source:deploy --verbose --wait=120 --manifest=build/artifact/package/package.xml --targetusername=target-org --testlevel=RunSpecifiedTests --runtests=${{ inputs.unit-tests }}
