name: 'Check Metadata Change'
description: 'Determines if there are Salesforce metadata changes.'

outputs:
  has-metadata-change:
    description: 'Value is true when there are Salesforce metadata changes.'
    value: ${{ steps.check-metadata-change.outputs.has-metadata-change }}

runs:
  using: "composite"
  steps:
    # make sure the order of arguments is correct in the command, i.e. git diff DESTINATION_BRANCH SOURCE_BRANCH
    - id: check-metadata-change
      run: |
        if [ -n "$(git --no-pager diff --diff-filter=ACMRTUXB --name-only remotes/origin/${{ github.base_ref }} remotes/origin/${{ github.head_ref }} | grep ^force-app)" ]; then
          echo "::set-output name=has-metadata-change::true"
          echo
          echo 'Found metadata change. Continue build.'
        else
          echo "::set-output name=has-metadata-change::false"
          echo
          echo "::notice title=Validate/Deploy Build Notice::No metadata change found. Skip build."
        fi
