name: Custom Check

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Commit hash from branch'
        required: true
        default: 'custom-check'

jobs:
  create-check-run:
    runs-on: ubuntu-latest
    outputs:
      data: ${{ steps.create-check-run.outputs.data }}
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: ${{ github.event.inputs.branch }}

      - name: Get Latest Commit Hash
        id: latest-commit-hash
        #uses: ./.github/actions/get-latest-commit-hash
        run: echo "::set-output name=commit-hash::$( git log -1 --format='%H' )"

      - name: Create Check Run
        uses: octokit/request-action@v2.1.0
        id: create-check-run
        with:
          route: POST /repos/${{ github.repository }}/check-runs
          name: ${{ github.workflow }}
          head_sha: ${{ steps.latest-commit-hash.outputs.commit-hash }}
          status: in_progress
          details_url: "https://google.com"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  validate-build:
    runs-on: ubuntu-latest
    steps:
      - name: Whats up
        run: echo "Hello World!"

  update-check-run:
    if: always()
    needs: [create-check-run, validate-build]
    runs-on: ubuntu-latest
    steps:
      - name: Update Check Run as Success
        if: success()
        uses: octokit/request-action@v2.x
        with:
          route: PATCH /repos/${{ github.repository }}/check-runs/${{ fromJson(needs.create-check-run.outputs.data).id }}
          check_run_id: ${{ fromJson(needs.create-check-run.outputs.data).id }}
          status: completed
          conclusion: success
          output: |
            title: Success
            summary: The validation build was successful.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Check Run as Failure
        if: failure()
        uses: octokit/request-action@v2.x
        with:
          route: PATCH /repos/${{ github.repository }}/check-runs/${{ fromJson(needs.create-check-run.outputs.data).id }}
          check_run_id: ${{ fromJson(needs.create-check-run.outputs.data).id }}
          status: completed
          conclusion: failure
          output: |
            title: Failure
            summary: The validation build has failed.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Check Run as Cancelled
        if: cancelled()
        uses: octokit/request-action@v2.x
        with:
          route: PATCH /repos/${{ github.repository }}/check-runs/${{ fromJson(needs.create-check-run.outputs.data).id }}
          check_run_id: ${{ fromJson(needs.create-check-run.outputs.data).id }}
          status: completed
          conclusion: cancelled
          details_url: "https://bing.com"
          output: |
            title: Cancelled
            summary: The validation build has been cancelled.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
