name: Custom Check

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Commit hash from branch'
        required: true
        default: 'custom-check'

jobs:
  build-info:
    name: Build Info
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Get Pull Requests
        uses: octokit/request-action@v2.1.0
        id: get-pull-requests
        with:
          route: GET /repos/${{ github.repository }}/pulls
          accept: application/vnd.github.v3+json
          state: open
          head: ${{ github.repository_owner }}:${{ github.event.inputs.branch }}
          base: develop
          sort: created
          direction: desc
          per_page: 100
          page: 1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Annotations
        run: |
          echo "::notice title=Build Info - Workflow::${{ github.server_url }}/${{ github.repository }}/actions/workflows/custom-check.yml"
          echo "::notice title=Build Info - Validating Branch::${{ github.event.inputs.branch }}"
          echo "::notice title=Build Info - Pull Request::PR #${{ fromJSON(steps.get-pull-requests.outputs.data)[0].number }} ${{ fromJSON(steps.get-pull-requests.outputs.data)[0].html_url }}"
