name: Custom Check

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Commit hash from branch'
        required: true
        default: 'custom-check'

jobs:
  custom-check-build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.branch }}

      - name: Get Latest Commit Hash
        id: latest-commit-hash
        run: echo "::set-output name=commit-hash::$( git log -1 --format='%H' )"

      - name: Create Check Run
        uses: octokit/request-action@v2.1.0
        id: create-check-run
        with:
          route: POST /repos/${{ github.repository }}/check-runs
          name: ${{ github.workflow }}
          head_sha: ${{ steps.latest-commit-hash.outputs.commit-hash }}
          status: in_progress
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Check Run
        uses: octokit/request-action@v2.x
        with:
          route: PATCH /repos/${{ github.repository }}/check-runs/${{ fromJson(steps.create-check-run.outputs.data).id }}
          check_run_id: ${{ fromJson(steps.create-check-run.outputs.data).id }}
          status: completed
          conclusion: success
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}