name: Partial SBX PR Validation
concurrency: 'partial-sbx'

on:
  pull_request:
    branches: develop

jobs:
  validate-build:
    runs-on: ubuntu-latest
    environment: PARTIAL_SBX
    steps:
      - uses: actions/checkout@v2

      - name: 'State Check'
        run: |
          git status --verbose --branch --long
          git branch -vv --all
          echo github.ref is: ${{ github.ref }}
          echo
          echo github.event_name is: ${{ github.event_name }}
          echo
          echo This workflow is running: ${{ github.workflow }}
          echo
          echo The actor is: ${{ github.actor }}
          echo
          echo the repo: ${{ github.repository }}
          echo
          echo event name: ${{ github.event_name }}
          echo
          echo the sha is: ${{ github.sha }}
          echo
          echo the ref is: ${{ github.ref }}
          echo
          echo the ref name is: ${{ github.ref_name }}
          echo
          echo the ref type is (branch or tag): ${{ github.ref_type }}
          echo
          echo the head branch is (from): ${{ github.head_ref }}
          echo
          echo the base branch is (mergin to): ${{ github.base_ref }}

      - name: 'Install SFDX CLI'
        run: |
          wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
          mkdir sfdx-cli
          tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
          ./sfdx-cli/install

      - name: 'Decrypt Server Key'
        run: openssl enc -nosalt -aes-256-cbc -d -in build/server.key.enc -out server.key -base64 -K ${{ secrets.DECRYPTION_KEY }} -iv ${{ secrets.DECRYPTION_IV }}

      - name: 'Authorize User in Org'
        run: sfdx force:auth:jwt:grant --clientid=${{ secrets.ORG_CONSUMER_KEY }} --username=${{ secrets.ORG_USERNAME }} --jwtkeyfile server.key --instanceurl=${{ secrets.ORG_INSTANCE_URL }} --setdefaultusername --setalias=target-org

      - name: 'Org List'
        run: sfdx force:org:list --all --verbose

      - name: 'Convert DX to Metadata'
        run: sfdx force:source:convert --rootdir=force-app --outputdir=src

      - name: 'Package XML Output'
        run: cat src/package.xml

      - name: 'Validate in Org'
        run: sfdx force:mdapi:deploy --wait=-1 --targetusername=target-org --deploydir=src --testlevel=RunLocalTests --checkonly