name: Partial SBX Deploy Manual
concurrency: 'partial-sbx'

on:
  workflow_dispatch:
    inputs:
      commit-hash:
        description: 'Commit hash from branch'
        required: true
        default: 'HEAD^'
      test-only:
        description: 'Test only?'
        required: true
        default: 'Yes'

jobs:
  deploy-build:
    runs-on: ubuntu-latest
    environment: PARTIAL_SBX
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 'Check for Metadata Change'
        id: check-metadata-change
        uses: ./.github/actions/check-metadata-change
        with:
          destination-branch: ${{ github.event.inputs.commit-hash }}
          source-branch: HEAD

      - name: 'Install SFDX CLI'
        run: |
          echo ${{ github.event.inputs.commit-hash }}
          echo ${{ github.event.inputs.test-only }}
          echo ${{ steps.check-metadata-change.outputs.has-metadata-change }}
          echo ${{ contains(github.event.inputs.test-only, 'Yes') }}
          echo 'validate'
          echo ${{ (steps.check-metadata-change.outputs.has-metadata-change == 'true') && contains(github.event.inputs.test-only, 'Yes') }}
          echo 'deploy'
          echo ${{ (steps.check-metadata-change.outputs.has-metadata-change == 'true') && contains(github.event.inputs.test-only, 'Yes') }}
          echo 'validate'
          echo ${{ steps.check-metadata-change.outputs.has-metadata-change == 'true' && contains(github.event.inputs.test-only, 'Yes') }}
          echo 'deploy'
          echo ${{ steps.check-metadata-change.outputs.has-metadata-change == 'true' && contains(github.event.inputs.test-only, 'Yes') }}