name: Production Deployment
concurrency: 'production'

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Release Description'
        default: 'Manual Release'
        required: true

jobs:
  deploy-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: 'Install SFDX CLI'
        run: |
          wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
          mkdir sfdx-cli
          tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
          ./sfdx-cli/install

      - name: 'Decrypt Server Key'
        run: openssl enc -nosalt -aes-256-cbc -d -in build/server.key.enc -out server.key -base64 -K ${{ secrets.DECRYPTION_KEY }} -iv ${{ secrets.DECRYPTION_IV }}

      - name: 'Authorize User in Org'
        run: |
          sfdx force:auth:jwt:grant --clientid=${{ secrets.CONSUMER_KEY }} --username=${{ secrets.USERNAME }} --jwtkeyfile server.key --instanceurl=${{ secrets.INSTANCE_URL }} --setdefaultusername --setalias=target-org
          sfdx force:org:list --all --verbose

      - name: 'Convert DX to Metadata'
        run: |
          sfdx force:source:convert --rootdir=force-app --outputdir=src
          cat src/package.xml

      - name: 'Deploy in Org'
        run: sfdx force:mdapi:deploy --wait=-1 --targetusername=target-org --deploydir=src --testlevel=RunLocalTests
